### ISSUE TITLE
依赖需求

### ISSUE THREAD

**Issue by MitchellRyrie-evanBuck** [Jimmylxue/JVlog#1]
希望集成以下依赖配置好
nativewind V4
react-native-reanimated

昨天正安装这两个卡住一点 博主有意向配置这两个 
配置好的话 踢我一下 我直接用你搭建的环境

**Comment by Jimmylxue** [comment]
已经处理好 可以看最新的commit

**Comment by MitchellRyrie-evanBuck** [comment]
> 已经处理好了可以看最新的commit

酷
